name: Maven CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configure Chrome for headless execution
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Build with Maven and Run Tests (Chrome Headless)
      run: mvn -B test --file pom.xml -Dwebdriver.chrome.driver=/usr/bin/google-chrome -Denv=qa
      env:
        DISPLAY: :99

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports